name: Alarm Handler
version: "1.0"
slug: alarm-handler
description: "Handles temperature alarms and sends SMS"
startup: application
boot: auto
hassio_api: true
homeassistant_api: false
options:
  mqtt_broker: 192.168.1.101
  mqtt_user: mqtt-user
  mqtt_pass: Skarpt
  sms_uri: http://192.168.1.101:3000/api/v1/sms/outbox
  sms_credentials: apiuser:pleasechangeme
  alarm_delay_minutes: 1
  cold_room_sensors: ["62210229", "62240894", "06240840", "87654321", "12345678"]
  normal_room_sensors: ["44443333", "66665555", "76543211", "88887777", "99998888"]
  phone_numbers: ["01140214856", "01116072004", "01123008561"]
schema:
  mqtt_broker: str
  mqtt_user: str
  mqtt_pass: password
  sms_uri: str
  sms_credentials: str
  alarm_delay_minutes: int
  cold_room_sensors:
    - str
  normal_room_sensors:
    - str
  phone_numbers:
    - str
